export interface DeliveryNoteData {
  noteNumber: string;
  issuedAt: Date;
  shippedAt?: Date | null;
  deliveredAt?: Date | null;
  carrierName?: string | null;
  trackingNumber?: string | null;
  notes?: string | null;
  signedBy?: string | null;
  order?: {
    orderNumber: string;
    shippingAddressLine1?: string | null;
    shippingAddressLine2?: string | null;
    shippingCity?: string | null;
    shippingState?: string | null;
    shippingCountryCode?: string | null;
  } | null;
  branch?: { name: string; address?: string | null; city?: string | null; phone?: string | null } | null;
}

export function generateDeliveryNoteHtml(note: DeliveryNoteData): string {
  const date = (d?: Date | null) => d ? new Date(d).toLocaleDateString() : '-';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Delivery Note ${note.noteNumber}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, sans-serif; font-size: 13px; color: #333; padding: 40px; }
  .header { display: flex; justify-content: space-between; margin-bottom: 32px; }
  .company-name { font-size: 24px; font-weight: bold; color: #1a1a2e; }
  .doc-title { font-size: 28px; font-weight: bold; color: #e67e22; text-align: right; }
  .doc-meta { text-align: right; color: #666; }
  .section { margin-bottom: 24px; }
  .section-title { font-weight: bold; color: #1a1a2e; border-bottom: 2px solid #e67e22; padding-bottom: 4px; margin-bottom: 8px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }
  .label { color: #666; font-size: 11px; text-transform: uppercase; }
  .value { font-weight: 500; }
  .signature-box { border: 1px solid #ccc; height: 80px; margin-top: 8px; display: flex; align-items: flex-end; padding: 8px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee; color: #999; font-size: 11px; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
<div class="header">
  <div>
    <div class="company-name">${note.branch?.name ?? 'Dazzling UM'}</div>
    ${note.branch?.address ? `<div>${note.branch.address}</div>` : ''}
    ${note.branch?.city ? `<div>${note.branch.city}</div>` : ''}
    ${note.branch?.phone ? `<div>${note.branch.phone}</div>` : ''}
  </div>
  <div>
    <div class="doc-title">DELIVERY NOTE</div>
    <div class="doc-meta">
      <div><strong>#${note.noteNumber}</strong></div>
      <div>Issued: ${date(note.issuedAt)}</div>
    </div>
  </div>
</div>

<div class="grid">
  <div class="section">
    <div class="section-title">Delivery Details</div>
    ${note.order ? `<p><span class="label">Order #</span><br /><span class="value">${note.order.orderNumber}</span></p><br />` : ''}
    <p><span class="label">Shipped</span><br /><span class="value">${date(note.shippedAt)}</span></p><br />
    <p><span class="label">Delivered</span><br /><span class="value">${date(note.deliveredAt)}</span></p>
  </div>

  <div class="section">
    <div class="section-title">Carrier</div>
    ${note.carrierName ? `<p><span class="label">Carrier</span><br /><span class="value">${note.carrierName}</span></p><br />` : ''}
    ${note.trackingNumber ? `<p><span class="label">Tracking #</span><br /><span class="value">${note.trackingNumber}</span></p>` : ''}
  </div>
</div>

${note.order && (note.order.shippingAddressLine1 || note.order.shippingCity) ? `
<div class="section">
  <div class="section-title">Delivery Address</div>
  ${note.order.shippingAddressLine1 ? `<p>${note.order.shippingAddressLine1}</p>` : ''}
  ${note.order.shippingAddressLine2 ? `<p>${note.order.shippingAddressLine2}</p>` : ''}
  <p>${[note.order.shippingCity, note.order.shippingState, note.order.shippingCountryCode].filter(Boolean).join(', ')}</p>
</div>
` : ''}

${note.notes ? `<div class="section"><div class="section-title">Notes</div><p>${note.notes}</p></div>` : ''}

<div class="section" style="margin-top: 40px">
  <div class="section-title">Recipient Signature</div>
  ${note.signedBy ? `<p><strong>Signed by:</strong> ${note.signedBy}</p>` : ''}
  <div class="signature-box">
    ${note.signedBy ? note.signedBy : '<span style="color:#ccc">Signature</span>'}
  </div>
</div>

<div class="footer">
  <p>Delivery Note generated by Dazzling UM ERP.</p>
</div>
</body>
</html>`;
}
