export interface ReceiptData {
  receiptNumber: string;
  issuedAt: Date;
  paymentMethod?: string;
  originalCurrencyCode: string;
  originalAmount: number;
  notes?: string | null;
  branch?: { name: string; address?: string | null; city?: string | null; phone?: string | null } | null;
}

export function generateReceiptHtml(receipt: ReceiptData): string {
  const fmt = (n: number) => `${receipt.originalCurrencyCode} ${Number(n).toFixed(2)}`;
  const date = (d: Date) => new Date(d).toLocaleDateString();
  const time = (d: Date) => new Date(d).toLocaleTimeString();

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Receipt ${receipt.receiptNumber}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Courier New', monospace; font-size: 13px; color: #333; padding: 40px; max-width: 400px; margin: 0 auto; }
  .header { text-align: center; border-bottom: 2px dashed #333; padding-bottom: 16px; margin-bottom: 16px; }
  .company-name { font-size: 20px; font-weight: bold; }
  .doc-title { font-size: 18px; margin-top: 8px; text-transform: uppercase; letter-spacing: 4px; }
  .row { display: flex; justify-content: space-between; padding: 4px 0; }
  .row.total { font-weight: bold; font-size: 16px; border-top: 2px dashed #333; padding-top: 8px; margin-top: 8px; }
  .divider { border-top: 1px dashed #333; margin: 8px 0; }
  .footer { text-align: center; margin-top: 24px; font-size: 11px; color: #666; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
<div class="header">
  <div class="company-name">${receipt.branch?.name ?? 'Dazzling UM'}</div>
  ${receipt.branch?.address ? `<div>${receipt.branch.address}</div>` : ''}
  ${receipt.branch?.city ? `<div>${receipt.branch.city}</div>` : ''}
  ${receipt.branch?.phone ? `<div>${receipt.branch.phone}</div>` : ''}
  <div class="doc-title">Receipt</div>
</div>

<div class="row"><span>Receipt #:</span><span>${receipt.receiptNumber}</span></div>
<div class="row"><span>Date:</span><span>${date(receipt.issuedAt)}</span></div>
<div class="row"><span>Time:</span><span>${time(receipt.issuedAt)}</span></div>
${receipt.paymentMethod ? `<div class="row"><span>Method:</span><span>${receipt.paymentMethod.replace(/_/g, ' ')}</span></div>` : ''}

<div class="divider"></div>
<div class="row total">
  <span>TOTAL PAID</span>
  <span>${fmt(receipt.originalAmount)}</span>
</div>

${receipt.notes ? `<div class="divider"></div><p style="text-align:center;font-size:11px">${receipt.notes}</p>` : ''}

<div class="footer">
  <p>Thank you for your payment!</p>
  <p>Generated by Dazzling UM ERP</p>
</div>
</body>
</html>`;
}
